export default async function TermsOfService({
  params,
}: {
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const isPt = lang === 'pt';

  return (
    <article className="max-w-4xl mx-auto py-12 px-4 prose prose-invert prose-lg">
      <h1 className="text-4xl font-bold tracking-tight mb-8 text-foreground">
        {isPt ? "Termos de Serviço" : "Terms of Service"}
      </h1>
      <p className="text-foreground-muted mb-6">
        {isPt ? "Última atualização: Agosto de 2026" : "Last updated: August 2026"}
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4 text-foreground">{isPt ? "1. Aceitação dos Termos" : "1. Acceptance of Terms"}</h2>
        <p className="text-foreground-muted">
          {isPt
            ? "Ao acessar o portal Little Mere News, você concorda em usar o serviço de acordo com estes termos e com as leis e regulamentos aplicáveis."
            : "By accessing the Little Mere News portal, you agree to use the service in accordance with these terms and applicable laws and regulations."}
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4 text-foreground">{isPt ? "2. Conteúdo e Fontes" : "2. Content and Sources"}</h2>
        <p className="text-foreground-muted">
          {isPt
            ? "Os resumos são inicialmente gerados por IA e podem ser editados posteriormente por administradores autorizados. Um link de fonte é exibido quando disponível; a aplicação possui fallback quando ele não está disponível. A fonte original deve ser consultada para o contexto completo, e um resumo de IA não equivale a fact-checking independente."
            : "Summaries are initially generated by AI and may later be edited by authorized administrators. A source link is shown when available; the application has a fallback when it is unavailable. The original source should be consulted for full context, and an AI summary is not independent fact-checking."}
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4 text-foreground">{isPt ? "3. Direitos de Conteúdo e Marcas" : "3. Content and Trademark Rights"}</h2>
        <p className="text-foreground-muted">
          {isPt
            ? "Material editorial original pertence aos respectivos titulares de direitos. A licença do software deste repositório não relicencia artigos de publishers, conteúdo de feeds, marcas, logos ou outros materiais editoriais de terceiros. Nomes e marcas das fontes permanecem de seus respectivos titulares, e a presença de uma fonte no produto não implica afiliação ou endosso."
            : "Original editorial material belongs to its respective rightsholders. This repository's software license does not relicense publisher articles, feed content, trademarks, logos, or other third-party editorial material. Source names and marks remain the property of their respective holders, and a source appearing in the product does not imply affiliation or endorsement."}
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4 text-foreground">{isPt ? "4. Limitações de Conteúdo" : "4. Content Limitations"}</h2>
        <p className="text-foreground-muted">
          {isPt
            ? "Saídas de IA podem conter erros, omissões, hallucinations ou drift de paráfrase, tradução e localização. A validação estruturada verifica o formato do payload, não a exatidão factual, e excertos ou truncamentos do feed podem limitar o contexto disponível."
            : "AI output may contain errors, omissions, hallucinations, or paraphrase, translation, and localization drift. Structured validation checks payload format rather than factual accuracy, and feed excerpts or truncation can limit the available context."}
        </p>
      </section>
    </article>
  );
}
